approve:
- commandHelpLink: ""
  repos:
  - openshift/ibm-vpc-block-csi-driver-operator
  require_self_approval: false
label:
  restricted_labels:
    openshift/ibm-vpc-block-csi-driver-operator:
    - allowed_teams:
      - openshift-patch-managers
      allowed_users:
      - dobsonj
      - jsafrane
      label: backport-risk-assessed
    - allowed_users:
      - ropatil010
      - duanwei33
      label: cherry-pick-approved
lgtm:
- repos:
  - openshift/ibm-vpc-block-csi-driver-operator
  review_acts_as_lgtm: true
plugins:
  openshift/ibm-vpc-block-csi-driver-operator:
    plugins:
    - approve
